@BaseAddress=https://localhost:5001

### Create Note
POST {{BaseAddress}}/notes
Content-Type: application/json
Accept: application/json

{
    "Title": "AI engineer",
    "Content": "A new role evolving in the software development space!"
}

### Get Notes
GET {{BaseAddress}}/notes
Accept: application/json